---
title: "Lab 2 - Map projections and CRS"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
        number_sections: yes
        theme: united
---

In this exercise you will learn:

1. Get to know the basics R packages to do GIS analysis
2. Get to know basic concepts related to spatial reference systems
3. Understand that different map projections make measurements of distance and area different
4. Be able to add a new field to the attribute table and calculate area values
5. Be able to define and change map projections

Submission:

You are required to submit a pdf file with two exported maps with area correct and perpendicular map projection. You must also take the test that belongs to learning module 2 (test 2).

# Introduction to the exercise

In this exercise, you will become familiar with geographical reference systems and map coordinate systems. We will also see how different map projections affect distance and area measurements.

**Map projection** is a way to convert geographical positions from a spherical system to a
flat coordinate system (Cartesian coordinate system). The problem with map projections
problem is that it can introduce errors through distorsion. Distortions can affect:

- Form
- Area
- Distance
- Direction

Note that during the exercise you will find questions in italic. You have to answer the questions.

> * What is a Cartesian coordinate system?




